networks:
    minecraft-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:

    playit:
        image: ghcr.io/playit-cloud/playit-agent:0.15
        network_mode: host
        environment:
            SECRET_KEY: ${SECRET_KEY}
        restart: always

    lazymc:
        image: ghcr.io/joesturge/lazymc-docker-proxy:latest    
        networks:
            minecraft-network:
                ipv4_address: 172.18.0.2
        restart: always
        volumes:        
            - /srv/docker/minecraft/allthemods:/server/allthemods:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "25565:25565"
            
    allthemods:
        image: 'itzg/minecraft-server:java21'
        networks:
            minecraft-network:
                ipv4_address: 172.18.0.4
        environment:
            TYPE: 'NEOFORGE'
            GENERIC_PACK: '/data/allthemods.zip'
 #           CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/6921534'
            MAX_PLAYERS: 10
            VERSION: 1.21.1
            ICON: 'https://media.forgecdn.net/avatars/thumbnails/1182/438/64/64/638755918649288941.png'
            CF_API_KEY: ${CF_API_KEY}
            MEMORY: 6G
            USE_AIKAR_FLAGS: 'true'
            PVP: 'false'
            ONLINE_MODE: 'FALSE'
            EULA: 'TRUE'
            DIFFICULTY: 'normal'
            OPS: ${OPS}
            ALLOW_FLIGHT: TRUE
            MOTD: | 
                \u00A7c +\u00A7r\u00A7m-----------\u00A7c+\u00A7r \u00A7e\u00A7lErick's Network\u00A7r \u00A7c+\u00A7r\u00A7m-----------\u00A7c+\u00A7r
                \u00A7c>\u00A74>\u00A7r \u00A7c\u00A7lMODPACK\u00A77: All the Mods 10 - ATM10  
            CURSEFORGE_FILES: |
                skinrestorer
                simple-voice-chat
            CF_EXCLUDE_MODS: |
                smithing-template-viewer
            # CF_FORCE_SYNCHRONIZE: 'true'
            ENABLE_RCON: "true"
            RCON_PASSWORD: "allthemodsRCON"
            RCON_PORT: "25575"
            CF_OVERRIDES_EXCLUSIONS: |
                shaderpacks/**
        volumes:
            - /srv/docker/minecraft/allthemods:/data
        labels:
            - lazymc.enabled=true        
            - lazymc.group=allthemods        
            - lazymc.server.address=allthemods:25565
            - lazymc.port=25565 
            - lazymc.public.version=1.21.1       
            - lazymc.server.directory=/server/allthemods
            - lazymc.time.minimum_online_time=300
        ports:
            - "24454:24454/udp"
        restart: 'no'
        stdin_open: true
        tty: true
        healthcheck:
            test: mc-health
            start_period: 1m
            interval: 5s
            retries: 20
      
    backup:
        image: itzg/mc-backup:latest
        depends_on:
            allthemods:
                condition: service_started
        networks:
            - minecraft-network
        environment:
            RCON_HOST: "allthemods"
            RCON_PORT: "25575"
            RCON_PASSWORD: "allthemodsRCON"
            BACKUP_INTERVAL: "2h"
            INITIAL_DELAY: "10m"
            BACKUP_METHOD: "tar"
            PAUSE_IF_NO_PLAYERS: "false"
            PRUNE_BACKUPS_DAYS: "3"
            RCON_RETRIES: "-1"          # tenta até o servidor estar ligado
            RCON_RETRY_INTERVAL: "1m"
            DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}  # coloque a sua
            POST_BACKUP_SCRIPT_FILE: "/scripts/post-backup-discord.sh"
        volumes:
            - /srv/docker/minecraft/allthemods:/data:ro
            - /srv/backups/allthemods:/backups
            - /srv/docker/minecraft/scripts/post-backup-discord.sh:/scripts/post-backup-discord.sh:ro